import jax
import jax.numpy as jnp
from jax import lax
import numpy as np
from dmipy_jax.utils.spherical_harmonics import sh_basis_real_analytic, cart2sphere

def generate_polynomial_curve(h_params, s_grid, order=3):
    """
    Generates a 3D curve from polynomial coefficients in Polar coordinates.
    
    Matches Aganj's logic:
    theta(s) = sum(h_theta[k] * s^k)
    phi(s)   = sum(h_phi[k] * s^k)
    
    x, y, z generated by integrating tangent vector (sin(th)cos(ph), ...).
    
    Args:
        h_params: (2 * order,) Array. [h_theta_0...h_theta_k, h_phi_0...h_phi_k]
        s_grid: (N_steps,) Array of arc lengths [0 ... L].
        order: Polynomial order.
    Returns:
        curve_points: (N_steps, 3) 3D coordinates.
    """
    # Split params
    h_theta = h_params[:order]
    h_phi = h_params[order:]
    
    # Polynomial evaluation
    # theta = h0 + h1*s + h2*s^2...
    # s_grid powers: (order, N_steps)
    s_powers = jnp.stack([s_grid**k for k in range(order)], axis=0)
    
    theta = h_theta @ s_powers # (N_steps,)
    phi = h_phi @ s_powers     # (N_steps,)
    
    # Tangent vectors
    # tangent = [sin(th)cos(ph), sin(th)sin(ph), cos(th)]
    sin_th = jnp.sin(theta)
    cos_th = jnp.cos(theta)
    sin_ph = jnp.sin(phi)
    cos_ph = jnp.cos(phi)
    
    tx = sin_th * cos_ph
    ty = sin_th * sin_ph
    tz = cos_th
    
    tangents = jnp.stack([tx, ty, tz], axis=1) # (N_steps, 3)
    
    # Integrate to get position
    # x(s) = integrate(t(s) ds)
    # Simple cumulative sum approximation
    # ds assumed constant from s_grid structure
    ds = s_grid[1] - s_grid[0]
    positions = jnp.cumsum(tangents, axis=0) * ds
    
    return positions, tangents

def sample_sh_field(sh_volume, coords):
    """
    Interpolates SH coefficients at continuous coordinates.
    sh_volume: (X, Y, Z, N_coeffs)
    coords: (N_points, 3) [0..X-1, 0..Y-1, 0..Z-1]
    """
    # Move channel to front for map_coordinates: (C, X, Y, Z)
    vol_T = jnp.moveaxis(sh_volume, -1, 0)
    
    def interp(vol_c):
        return jax.scipy.ndimage.map_coordinates(vol_c, coords.T, order=1, mode='constant', cval=0.0)
    
    samples = jax.vmap(interp)(vol_T) # (C, N_points)
    return samples.T # (N_points, C)

def score_curve_at_seed(h_params, seed_pos, sh_volume, s_grid, lmax=4):
    """
    Scores a single curve hypothesis starting at 'seed_pos'.
    
    Args:
        h_params: Curve shape parameters.
        seed_pos: (3,) Start position (voxel coords).
        sh_volume: (X, Y, Z, C) Coefficient volume.
        s_grid: Arc length steps.
    """
    # 1. Generate curve shape (relative to 0,0,0)
    rel_pos, tangents = generate_polynomial_curve(h_params, s_grid, order=int(h_params.shape[0]//2))
    
    # 2. Absolute positions
    abs_pos = seed_pos + rel_pos 
    
    # 3. Sample ODF coefficients along path
    # (N_points, C)
    local_sh = sample_sh_field(sh_volume, abs_pos)
    
    # 4. Evaluate ODF along tangent directions
    # tangents: (N_points, 3)
    r, theta, phi = cart2sphere(tangents[:,0], tangents[:,1], tangents[:,2])
    
    # Basis: (N_points, C)
    basis = sh_basis_real_analytic(theta, phi, lmax)
    
    # ODF values = sum(c * Y)
    odf_vals = jnp.sum(local_sh * basis, axis=1)
    
    # 5. Integrate Score
    # Score = sum(ODF(s)) (approximates integral if ds constant)
    # Aganj uses: Score = sum( log(max(ODF,0) + eps) + Prior )
    # Let's stick to simple sum for now, or match Aganj's log probability.
    # HoughTract.m: H(legitX) = log(max(odf, 0) + .02) + pVol(indX);
    
    score_elements = jnp.log(jnp.maximum(odf_vals, 0) + 0.02)
    total_score = jnp.sum(score_elements)
    
    return total_score

def global_hough_tracking(sh_volume, seeds, n_hough_samples=1000):
    """
    Runs Global Hough Tractography.
    
    Args:
        sh_volume: SH coefficients.
        seeds: (N_seeds, 3) Seed points.
        n_hough_samples: Number of random curves to test per seed (for MCMC/Random Search).
                         Or grid size if using grid.
    
    Returns:
        best_curves: (N_seeds, N_steps, 3)
        best_scores: (N_seeds,)
    """
    N_seeds = seeds.shape[0]
    
    # Grid setup
    s_grid = jnp.linspace(0, 5.0, 50) # 5mm length?
    
    # Random Search Logic (Monte Carlo Hough)
    # Instead of exhaustive grid, we sample random polynomials.
    # h_params: (N_samples, 2*order)
    order = 3
    key = jax.random.PRNGKey(42)
    h_samples = jax.random.normal(key, (n_hough_samples, 2*order)) * 0.5
    
    # We want to find the BEST h_sample for EACH seed.
    # Efficient strategy:
    # vmap over seeds? (N_seeds * N_samples = huge)
    # scan over samples?
    
    # State: best_score (N_seeds,), best_h (N_seeds, 2*order)
    init_score = jnp.full((N_seeds,), -jnp.inf)
    init_h = jnp.zeros((N_seeds, 2*order))
    
    def scan_body(carry, h_batch):
        # carry: (current_best_scores, current_best_h)
        # h_batch: (BatchSize, 2*order) - current set of curves to test
        # We test this ONE batch of curves against ALL seeds?
        # Aganj's "Global" means the curve shape H is global, but position depends on seed.
        # Yes: For a given H (shape), we place it at every seed and score it.
        
        curr_scores, curr_h = carry
        
        # vmap score_curve_at_seed over seeds, with fixed h (broadcasted?)
        # h_batch is actually a single H or a small batch? 
        # Let's simplify: scan over ONE h_param at a time (or small chunks).
        
        # h_param: (2*order,)
        h_cand = h_batch
        
        # Score this single H shape at ALL seeds
        # vmap over seeds
        scores = jax.vmap(lambda s: score_curve_at_seed(h_cand, s, sh_volume, s_grid))(seeds)
        
        # Update Best
        improved = scores > curr_scores
        new_scores = jnp.where(improved, scores, curr_scores)
        new_h = jnp.where(improved[:, None], h_cand[None, :], curr_h)
        
        return (new_scores, new_h), None

    # Run Scan
    (final_scores, final_h), _ = lax.scan(scan_body, (init_score, init_h), h_samples)
    
    # Reconstruct curves
    def get_curve(h, s):
        rel, _ = generate_polynomial_curve(h, s_grid, order)
        return s + rel
        
    final_curves = jax.vmap(get_curve)(final_h, seeds)
    
    return final_curves, final_scores
