import os
import json
import base64

def generate_report():
    base_dir = "/home/mhough/datasets/ds001957-study/derivatives/super_resolution/sub-01/dwi"
    
    # Load Metrics
    metrics_path = os.path.join(base_dir, "metrics.json")
    metrics = {}
    if os.path.exists(metrics_path):
        with open(metrics_path, "r") as f:
            metrics = json.load(f)
            
    # HTML Content
    html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Super-Resolution Report: sub-01</title>
        <style>
            :root {{
                --primary: #2563eb;
                --surface: #ffffff;
                --background: #f8fafc;
                --text: #1e293b;
            }}
            body {{
                font-family: 'Inter', system-ui, -apple-system, sans-serif;
                background-color: var(--background);
                color: var(--text);
                margin: 0;
                padding: 2rem;
                line-height: 1.5;
            }}
            .container {{
                max_width: 1200px;
                margin: 0 auto;
            }}
            h1 {{
                font-size: 2.5rem;
                font-weight: 800;
                margin-bottom: 0.5rem;
                background: linear-gradient(to right, #2563eb, #7c3aed);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
            }}
            .card {{
                background: var(--surface);
                border-radius: 1rem;
                box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1);
                padding: 1.5rem;
                margin-bottom: 2rem;
            }}
            .grid-img {{
                width: 100%;
                border-radius: 0.5rem;
                border: 1px solid #e2e8f0;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 1rem;
            }}
            th, td {{
                text-align: left;
                padding: 1rem;
                border-bottom: 1px solid #e2e8f0;
            }}
            th {{
                font-weight: 600;
                color: #64748b;
                text-transform: uppercase;
                font-size: 0.875rem;
            }}
            .metric-val {{
                font-family: 'JetBrains Mono', monospace;
                font-weight: 600;
            }}
            .best-score {{
                color: #16a34a;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <header style="margin-bottom: 3rem;">
                <h1>Super-Resolution Report</h1>
                <p style="color: #64748b; font-size: 1.125rem;">Subject: sub-01 | Modality: Diffusion MRI (1.5T -> 1mm T1w)</p>
            </header>

            <div class="card">
                <h2 style="margin-top: 0;">Quantitative Metrics</h2>
                <p>Gradient Magnitude Correlation with High-Res T1w Reference.</p>
                <table>
                    <thead>
                        <tr>
                            <th>Method</th>
                            <th>Gradient Correlation</th>
                        </tr>
                    </thead>
                    <tbody>
    """
    
    # Sort metrics by score (descending = closer to 1, but ours are negative so closer to 0 is better?)
    # Wait, correlation ranges [-1, 1]. Higher is better.
    # Our scores are negative. So max() is best.
    
    sorted_metrics = sorted(metrics.items(), key=lambda x: x[1] if isinstance(x[1], float) else -999, reverse=True)
    
    for name, score in sorted_metrics:
        score_str = f"{score:.4f}" if isinstance(score, float) else str(score)
        
        # Highlight best?
        is_best = (score == sorted_metrics[0][1])
        cls = "metric-val best-score" if is_best else "metric-val"
        
        html += f"""
                        <tr>
                            <td>{name}</td>
                            <td class="{cls}">{score_str}</td>
                        </tr>
        """
        
    html += """
                    </tbody>
                </table>
            </div>

            <div class="card">
                <h2 style="margin-top: 0;">Visual Comparison</h2>
                <p>2x4 Layout: Top Row (Full Slice), Bottom Row (Zoomed Details + INR).</p>
                <img src="comparison_grid.png" alt="Super Resolution Comparison" class="grid-img">
            </div>
            
            <footer style="text-align: center; color: #94a3b8; margin-top: 4rem;">
                <p>Generated by dmipy-jax agent</p>
            </footer>
        </div>
    </body>
    </html>
    """
    
    out_path = os.path.join(base_dir, "report.html")
    with open(out_path, "w") as f:
        f.write(html)
        
    print(f"Generated web report: {out_path}")

if __name__ == "__main__":
    generate_report()
